# Generated by Django 5.1.1 on 2024-12-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_name', models.CharField(max_length=100)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='weekly_lessons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_lessons', to='teachers.course')),
            ],
        ),
    ]
