# Generated by Django 5.1.1 on 2024-12-30 17:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_quizquestion_options_quizquestion_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylesson',
            name='content_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='weekly_lessons/'),
        ),
    ]
